# Generated by Django 5.2.8 on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normal_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="normaluser",
            name="username",
            field=models.CharField(max_length=50, unique=True, null=True, blank=True),
        ),
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, null=True, blank=True)),
                ("phone", models.CharField(max_length=20, null=True, blank=True)),
                ("password", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
