# Generated by Django 5.2.8 on 2025-12-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normal_users", "0007_moderationaction_userrestriction"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="last_approved_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pending_reapproval", "Pending Re-Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="PostVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "editor_admin_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("editor_role", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("mode", models.CharField(max_length=32)),
                ("main_text", models.TextField(blank=True)),
                (
                    "items_json",
                    models.TextField(
                        blank=True,
                        help_text="JSON array of item snapshots: media_type, file_url, caption_text, order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "editor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="normal_users.normaluser",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="normal_users.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-version"],
                "unique_together": {("post", "version")},
            },
        ),
    ]
