# Generated by ChatGPT for adding Feedback model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('normal_users', '0008_post_last_approved_version_alter_post_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='normal_users.normaluser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='normal_users.post')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status', 'created_at'], name='normal_user_status__8a8c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['post', 'status'], name='normal_user_post_id__b1c8b3_idx'),
        ),
    ]
