# Generated by Django 5.2.8 on 2025-12-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("normal_users", "0009_feedback"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="feedback",
            new_name="normal_user_status_4bd267_idx",
            old_name="normal_user_status__8a8c3e_idx",
        ),
        migrations.RenameIndex(
            model_name="feedback",
            new_name="normal_user_post_id_73f5df_idx",
            old_name="normal_user_post_id__b1c8b3_idx",
        ),
    ]
