# Generated by Django 5.2.8 on 2026-01-02 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_auth", "0001_initial"),
        (
            "normal_users",
            "0010_rename_normal_user_status__8a8c3e_idx_normal_user_status_4bd267_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="admin_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_posts",
                to="admin_auth.adminaccount",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="created_by_role",
            field=models.CharField(
                blank=True,
                help_text="normal | admin | superadmin",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="normal_users.normaluser",
            ),
        ),
        migrations.CreateModel(
            name="UserTokenBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_balance",
                        to="normal_users.normaluser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(choices=[("like", "Like")], max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="normal_users.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="normal_users.normaluser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["post", "reaction_type"],
                        name="normal_user_post_id_a7eb64_idx",
                    ),
                    models.Index(
                        fields=["user", "reaction_type"],
                        name="normal_user_user_id_b966da_idx",
                    ),
                ],
                "unique_together": {("user", "post", "reaction_type")},
            },
        ),
        migrations.CreateModel(
            name="RewardTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("like", "Like"),
                            ("comment", "Comment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_transactions",
                        to="normal_users.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_transactions",
                        to="normal_users.normaluser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="normal_user_user_id_d55b30_idx"
                    ),
                    models.Index(
                        fields=["post", "action_type"],
                        name="normal_user_post_id_1db80a_idx",
                    ),
                ],
                "unique_together": {("user", "post", "action_type")},
            },
        ),
    ]
