# Generated by Django 5.2.8 on 2026-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normal_users", "0012_rewardtransaction_reward_amount_wallet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdrawrequest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="rewardtransaction",
            name="reward_amount",
        ),
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name="Wallet",
        ),
        migrations.DeleteModel(
            name="WithdrawRequest",
        ),
    ]
