# Generated by Django 5.2.8 on 2026-02-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normal_users", "0013_remove_withdrawrequest_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_views",
                        to="normal_users.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_views",
                        to="normal_users.normaluser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "post"], name="normal_user_user_id_0a896d_idx"
                    )
                ],
                "unique_together": {("user", "post")},
            },
        ),
    ]
