# Generated by Django 5.2.8 on 2026-02-12 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normal_users", "0014_postview"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(default=0)),
                ("content", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("reply_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="normal_users.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="normal_users.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="normal_users.normaluser",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["post", "parent", "created_at"],
                        name="normal_user_post_id_e0c0d1_idx",
                    ),
                    models.Index(
                        fields=["post", "created_at"],
                        name="normal_user_post_id_f5a5bf_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="normal_user_user_id_f81a3d_idx",
                    ),
                    models.Index(
                        fields=["parent", "created_at"],
                        name="normal_user_parent__4a24db_idx",
                    ),
                ],
            },
        ),
    ]
