# Generated by Django 5.2.8 on 2026-02-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_auth", "0001_initial"),
        ("normal_users", "0015_post_comment_count_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="normaluser",
            name="allow_discovery",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="If false, user is excluded from discovery/search.",
            ),
        ),
        migrations.AddField(
            model_name="normaluser",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="normaluser",
            name="full_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="normaluser",
            name="is_private",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["created_at"], name="normal_user_created_a3e931_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "created_at"], name="normal_user_author__5d0d43_idx"
            ),
        ),
        migrations.AddField(
            model_name="userblock",
            name="blocked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks_received",
                to="normal_users.normaluser",
            ),
        ),
        migrations.AddField(
            model_name="userblock",
            name="blocker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks_initiated",
                to="normal_users.normaluser",
            ),
        ),
        migrations.AddField(
            model_name="userfollow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_relations",
                to="normal_users.normaluser",
            ),
        ),
        migrations.AddField(
            model_name="userfollow",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower_relations",
                to="normal_users.normaluser",
            ),
        ),
        migrations.AddIndex(
            model_name="userblock",
            index=models.Index(
                fields=["blocker", "blocked"], name="normal_user_blocker_ddfb86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userblock",
            index=models.Index(
                fields=["blocked", "blocker"], name="normal_user_blocked_ccdaf5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userblock",
            unique_together={("blocker", "blocked")},
        ),
        migrations.AddIndex(
            model_name="userfollow",
            index=models.Index(
                fields=["following", "created_at"],
                name="normal_user_followi_10a842_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userfollow",
            index=models.Index(
                fields=["follower", "created_at"], name="normal_user_followe_d4313c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together={("follower", "following")},
        ),
    ]
