# Generated by Django 5.2.8 on 2026-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "normal_users",
            "0016_userblock_userfollow_normaluser_allow_discovery_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="normaluser",
            name="account_type",
            field=models.CharField(
                choices=[("person", "Person"), ("advertiser", "Advertiser")],
                default="person",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="normaluser",
            name="organization_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="normaluser",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="normaluser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="normaluser",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="account_type",
            field=models.CharField(
                choices=[("person", "Person"), ("advertiser", "Advertiser")],
                default="person",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="organization_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
