# Generated by Django 5.2.8 on 2026-02-23 10:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("normal_users", "0017_normaluser_account_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postreaction",
            name="reaction_type",
            field=models.CharField(
                choices=[("like", "Like"), ("dislike", "Dislike")], max_length=16
            ),
        ),
        migrations.CreateModel(
            name="AdReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_reviews",
                        to="normal_users.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_reviews",
                        to="normal_users.normaluser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["post", "created_at"],
                        name="normal_user_post_id_d44f95_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="normal_user_user_id_25493a_idx",
                    ),
                ],
                "unique_together": {("post", "user")},
            },
        ),
        migrations.CreateModel(
            name="PostShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="normal_users.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_shares",
                        to="normal_users.normaluser",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["post", "created_at"],
                        name="normal_user_post_id_1aa33e_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="normal_user_user_id_218a94_idx",
                    ),
                ],
            },
        ),
    ]
