"""
Django settings for truepost project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-df0h8)-5cl0$^n37i#uor_823eai!mwf@dep(2zx%91hqdv!t2"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = [ 'localhost', '192.168.1.189',"127.0.0.1"]
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "normal_users",
    "admin_auth",
    "channels",
    "chat",
    'cloudinary',
    'cloudinary_storage',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "truepost.urls"
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "truepost.wsgi.application"
ASGI_APPLICATION = "truepost.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True,
    )
}


# DATABASES = {
#     'default': dj_database_url.parse(
#         os.environ.get('DATABASE_URL')
#     )
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'truepost',
#         'USER': 'postgres',
#         'PASSWORD': 'Inno-997',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#postgresql://truepost_user:7IgH7Fr3J4WVzA7fq6JE5pGxhY0D0W7c@dpg-d51e5qre5dus739t0av0-a/truepost

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 1. Static Configuration
STATIC_URL = '/static/'

# Directories where Django will look for YOUR custom static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# 🌟 2. CRITICAL FIX: The destination folder for collectstatic 🌟
# This is where all files (including Summernote's) will be gathered.
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# 3. Media Configuration (Needed for Summernote uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # Keep session auth for Django admin and browsable API
        "rest_framework.authentication.SessionAuthentication",
        # Custom JWT auth for Normal Users
        "normal_users.authentication.NormalUserJWTAuthentication",
        # Token auth for admin-only endpoints
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# Channels configuration (in-memory layer for development)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

# Email configuration (console by default; replace in production)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'innocentphilbert39@gmail.com'
EMAIL_HOST_PASSWORD = 'lxtc pnvq lboz czed'

DEFAULT_FROM_EMAIL = 'TruePost Verifications <innocentphilbert39@gmail.com>'

# Normal user auth settings
NORMAL_USER_JWT_SECRET = SECRET_KEY
NORMAL_USER_JWT_ACCESS_MINUTES = 4320
NORMAL_USER_JWT_REFRESH_DAYS = 7
NORMAL_USER_OTP_MINUTES = 10
NORMAL_USER_VERIFY_TOKEN_HOURS = 24
# NORMAL_USER_EMAIL_VERIFY_URL = "http://192.168.1.189:8000/api/auth/verify-email/"
NORMAL_USER_EMAIL_VERIFY_URL = "https://trustpost-platform.onrender.com/api/auth/verify-email/"
NORMAL_USER_PASSWORD_RESET_URL = "/api/auth/password-reset/confirm/"
# lxtc pnvq lboz czed app password from gmail 

# Reward system defaults (coins)
# Per requirements: View=10, Like=20, Comment=30
REWARD_VIEW_TOKENS = 10
REWARD_LIKE_TOKENS = 20
REWARD_COMMENT_TOKENS = 30
# Daily reward limits per action (configurable)
REWARD_VIEW_DAILY_LIMIT = int(os.environ.get("REWARD_VIEW_DAILY_LIMIT", 50))
REWARD_LIKE_DAILY_LIMIT = int(os.environ.get("REWARD_LIKE_DAILY_LIMIT", 20))
REWARD_COMMENT_DAILY_LIMIT = int(os.environ.get("REWARD_COMMENT_DAILY_LIMIT", 10))
