from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    NormalUserListView,
    UserDiscoverView,
    UserSearchView,
    UserPublicProfileView,
    UserPublicPostsView,
    RequestEmailVerificationView,
    VerifyEmailView,
    PasswordResetRequestView,
    PasswordResetVerifyOTPView,
    PasswordResetConfirmView,
    refresh_view,
    logout_view,
    me_view,
    MeUpdateView,
    MeAvatarUploadView,
    MePostListCreateView,
    MePostEditView,
    MeRestrictionsView,
    MeUploadMediaView,
    AdminUploadMediaView,
    AdminPendingPostsListView,
    AdminRejectedPostsListView,
    AdminPostCreateView,
    AdminPublishPostView,
    AdminApprovePostView,
    AdminRejectPostView,
    AdminUpdateRejectionReasonView,
    AdminEditPostView,
    AdminRollbackPostView,
    AdminDeletePostView,
    AdminIssueWarningView,
    AdminApplyRestrictionView,
    PublicApprovedPostsView,
    SubmitFeedbackView,
    ToggleLikeView,
    RecordViewRewardView,
    MeTokenBalanceView,
    MeRewardHistoryView,
    AdminPendingFeedbackListView,
    AdminApprovedFeedbackListView,
    AdminRejectedFeedbackListView,
    AdminApproveFeedbackView,
    AdminRejectFeedbackView,
    PublicApprovedFeedbackByPostView,
    MyRejectedFeedbackListView,
    EditRejectedFeedbackView,
    PostCommentListCreateView,
    CommentReplyListCreateView,
    CommentDetailView,
    # DemoWithdrawRequestView,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="nu-register"),
    path("login/", LoginView.as_view(), name="nu-login"),
    path("users/", NormalUserListView.as_view(), name="nu-users-list"),
    path("users/discover/", UserDiscoverView.as_view(), name="nu-users-discover"),
    path("users/search/", UserSearchView.as_view(), name="nu-users-search"),
    path("users/<int:pk>/", UserPublicProfileView.as_view(), name="nu-user-detail"),
    path("users/<int:pk>/posts/", UserPublicPostsView.as_view(), name="nu-user-posts"),
    path("refresh/", refresh_view, name="nu-refresh"),
    path("logout/", logout_view, name="nu-logout"),

    path("request-email-verification/", RequestEmailVerificationView.as_view(), name="nu-request-email-verification"),
    path("verify-email/", VerifyEmailView.as_view(), name="nu-verify-email"),

    path("password-reset/request/", PasswordResetRequestView.as_view(), name="nu-password-reset-request"),
    path("password-reset/verify-otp/", PasswordResetVerifyOTPView.as_view(), name="nu-password-reset-verify-otp"),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view(), name="nu-password-reset-confirm"),

    path("me/", me_view, name="nu-me"),
    path("me/update/", MeUpdateView.as_view(), name="nu-me-update"),
    path("me/avatar/", MeAvatarUploadView.as_view(), name="nu-me-avatar"),
    path("me/posts/", MePostListCreateView.as_view(), name="nu-me-posts"),
    path("me/posts/<int:pk>/edit/", MePostEditView.as_view(), name="nu-me-post-edit"),
    path("me/restrictions/", MeRestrictionsView.as_view(), name="nu-me-restrictions"),
    path("me/rewards/balance/", MeTokenBalanceView.as_view(), name="nu-me-rewards-balance"),
    path("me/rewards/history/", MeRewardHistoryView.as_view(), name="nu-me-rewards-history"),
    path("me/posts/upload-media/", MeUploadMediaView.as_view(), name="nu-me-upload-media"),
    path("admin/posts/upload-media/", AdminUploadMediaView.as_view(), name="admin-upload-media"),
    # Admin post authoring
    path("admin/posts/create/", AdminPostCreateView.as_view(), name="admin-post-create"),
    path("admin/posts/pending/", AdminPendingPostsListView.as_view(), name="admin-posts-pending"),
    path("admin/posts/rejected/", AdminRejectedPostsListView.as_view(), name="admin-posts-rejected"),
    path("admin/posts/<int:pk>/publish/", AdminPublishPostView.as_view(), name="admin-post-publish"),
    path("admin/posts/<int:pk>/approve/", AdminApprovePostView.as_view(), name="admin-post-approve"),
    path("admin/posts/<int:pk>/reject/", AdminRejectPostView.as_view(), name="admin-post-reject"),
    path("admin/posts/<int:pk>/reject/reason/", AdminUpdateRejectionReasonView.as_view(), name="admin-post-reject-reason"),
    path("admin/posts/<int:pk>/edit/", AdminEditPostView.as_view(), name="admin-post-edit"),
    path("admin/posts/<int:pk>/rollback/<int:version>/", AdminRollbackPostView.as_view(), name="admin-post-rollback"),
    path("admin/posts/<int:pk>/", AdminDeletePostView.as_view(), name="admin-post-delete"),
    path("admin/warn/", AdminIssueWarningView.as_view(), name="admin-warn"),
    path("admin/restrict/", AdminApplyRestrictionView.as_view(), name="admin-restrict"),
    path("posts/public/", PublicApprovedPostsView.as_view(), name="posts-public"),
    # Interactions and rewards
    path("posts/like/toggle/", ToggleLikeView.as_view(), name="posts-like-toggle"),
    path("posts/view/reward/", RecordViewRewardView.as_view(), name="posts-view-reward"),
    # Feedback endpoints
    path("feedback/submit/", SubmitFeedbackView.as_view(), name="feedback-submit"),
    path("admin/feedback/pending/", AdminPendingFeedbackListView.as_view(), name="admin-feedback-pending"),
    path("admin/feedback/approved/", AdminApprovedFeedbackListView.as_view(), name="admin-feedback-approved"),
    path("admin/feedback/rejected/", AdminRejectedFeedbackListView.as_view(), name="admin-feedback-rejected"),
    path("admin/feedback/<int:pk>/approve/", AdminApproveFeedbackView.as_view(), name="admin-feedback-approve"),
    path("admin/feedback/<int:pk>/reject/", AdminRejectFeedbackView.as_view(), name="admin-feedback-reject"),
    path("feedback/approved/by-post/<int:pk>/", PublicApprovedFeedbackByPostView.as_view(), name="feedback-approved-by-post"),
    path("feedback/rejected/mine/", MyRejectedFeedbackListView.as_view(), name="feedback-rejected-mine"),
    path("feedback/<int:pk>/edit/", EditRejectedFeedbackView.as_view(), name="feedback-edit"),
    # Nested comment system
    path("posts/<int:pk>/comments/", PostCommentListCreateView.as_view(), name="post-comments"),
    path("comments/<int:pk>/replies/", CommentReplyListCreateView.as_view(), name="comment-replies"),
    path("comments/<int:pk>/", CommentDetailView.as_view(), name="comment-detail"),
]
