from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    RequestEmailVerificationView,
    VerifyEmailView,
    PasswordResetRequestView,
    PasswordResetVerifyOTPView,
    PasswordResetConfirmView,
    refresh_view,
    logout_view,
    me_view,
    MeUpdateView,
    MeAvatarUploadView,
    MePostListCreateView,
    MeRestrictionsView,
    MeUploadMediaView,
    AdminPendingPostsListView,
    AdminApprovePostView,
    AdminRejectPostView,
    AdminIssueWarningView,
    AdminApplyRestrictionView,
    PublicApprovedPostsView,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="nu-register"),
    path("login/", LoginView.as_view(), name="nu-login"),
    path("refresh/", refresh_view, name="nu-refresh"),
    path("logout/", logout_view, name="nu-logout"),

    path("request-email-verification/", RequestEmailVerificationView.as_view(), name="nu-request-email-verification"),
    path("verify-email/", VerifyEmailView.as_view(), name="nu-verify-email"),

    path("password-reset/request/", PasswordResetRequestView.as_view(), name="nu-password-reset-request"),
    path("password-reset/verify-otp/", PasswordResetVerifyOTPView.as_view(), name="nu-password-reset-verify-otp"),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view(), name="nu-password-reset-confirm"),

    path("me/", me_view, name="nu-me"),
    path("me/update/", MeUpdateView.as_view(), name="nu-me-update"),
    path("me/avatar/", MeAvatarUploadView.as_view(), name="nu-me-avatar"),
    path("me/posts/", MePostListCreateView.as_view(), name="nu-me-posts"),
    path("me/restrictions/", MeRestrictionsView.as_view(), name="nu-me-restrictions"),
    path("me/posts/upload-media/", MeUploadMediaView.as_view(), name="nu-me-upload-media"),
    path("admin/posts/pending/", AdminPendingPostsListView.as_view(), name="admin-posts-pending"),
    path("admin/posts/<int:pk>/approve/", AdminApprovePostView.as_view(), name="admin-post-approve"),
    path("admin/posts/<int:pk>/reject/", AdminRejectPostView.as_view(), name="admin-post-reject"),
    path("admin/warn/", AdminIssueWarningView.as_view(), name="admin-warn"),
    path("admin/restrict/", AdminApplyRestrictionView.as_view(), name="admin-restrict"),
    path("posts/public/", PublicApprovedPostsView.as_view(), name="posts-public"),
]
